In [0]:
!pip install pytorch

  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
    Running setup.py install for pytorch ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-34hkl_1q/pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-34hkl_1q/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0emkvaou/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.


In [2]:
import torch
x = torch.Tensor([5,3])
y = torch.Tensor([2,2])
print(x*y)

tensor([10.,  6.])


In [0]:
x=torch.zeros([2,5])

In [6]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
x.shape

torch.Size([2, 5])

In [0]:
y=torch.rand([2,5])

In [9]:
y

tensor([[0.2415, 0.0443, 0.9531, 0.3655, 0.2026],
        [0.1321, 0.5949, 0.8517, 0.6319, 0.1989]])

In [10]:
y.view([1,10])

tensor([[0.2415, 0.0443, 0.9531, 0.3655, 0.2026, 0.1321, 0.5949, 0.8517, 0.6319,
         0.1989]])